[workspace]
resolver = "2"
members = [
    "crates/atom-skygaze",
    "crates/isvp-sys",
    "crates/mxu",
    "crates/solver"
]

[patch.crates-io]
fitsio-sys = { path = "./submodules/rust-fitsio/fitsio-sys" }
