#!/bin/sh

[ -f /etc/environment ] && . /etc/environment

/etc/init.d/S01syslogd start
/etc/init.d/S02klogd start
/etc/init.d/S02sysctl start
/etc/init.d/S10mdev start
/etc/init.d/S15gpio start
/etc/init.d/S34mountfs start
insmod /atom/system/driver/tx-isp-t31.ko isp_clk=100000000
insmod /atom/system/driver/avpu.ko
insmod /atom/system/driver/sinfo.ko
insmod /atom/system/driver/audio.ko spk_gpio=-1
insmod /atom/system/driver/sample_pwm_core.ko
insmod /atom/system/driver/sample_pwm_hal.ko
insmod /atom/system/driver/speaker_ctl.ko
insmod /atom/system/driver/sensor_gc2053_t31.ko data_interface=1
# Start all init scripts in /etc/init.d
# executing them in numerical order.
#
#for i in /etc/init.d/S??* ;do

     # Ignore dangling symlinks (if any).
#     [ ! -f "$i" ] && continue

#     case "$i" in
#	*.sh)
	    # Source shell script for speed.
#	    (
#		trap - INT QUIT TSTP
#		set start
#		. $i
#	    )
#	    ;;
#	*)
	    # No sh extension, so fork subprocess.
#	    $i start
#	    ;;
 #   esac
#done

