#!/bin/sh
#
# Start network time daemon
#

case "$1" in
  start)
    /usr/sbin/ntpd -q -g
    echo "NTP started successfully."
  ;;
  stop)
    logger -s "Stopping ntpd: "
    killall ntpd
    [ $? == 0 ] && logger -s "OK" || logger -s "FAIL"
  ;;
  restart|reload)
    "$0" stop
    "$0" start
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?