#!/bin/sh
#
# Start network time daemon
#

config_file="/media/mmc/atom_config.toml"
get_value() {
  grep "^$1" "$config_file" | awk -F ' = ' '{print $2}' | tr -d '"'
}

if [ -f "$config_file" ]; then
  ap_mode=$(get_value "ap_mode")

  if [[ "$ap_mode" == "true" ]]; then
    exit $?
  fi
fi

case "$1" in
  start)
    /usr/sbin/ntpd -q -g
    echo "NTP started successfully."
  ;;
  stop)
    logger -s "Stopping ntpd: "
    killall ntpd
    [ $? == 0 ] && logger -s "OK" || logger -s "FAIL"
  ;;
  restart|reload)
    "$0" stop
    "$0" start
  ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit $?