#!/bin/sh
#
# avahi-daemon init script

config_file="/media/mmc/atom_config.toml"
get_value() {
  grep "^$1" "$config_file" | awk -F ' = ' '{print $2}' | tr -d '"'
}

if [ -f "$config_file" ]; then
  ap_mode=$(get_value "ap_mode")

  if [[ "$ap_mode" == "true" ]]; then
    exit $?
  fi
fi

DAEMON=/usr/sbin/avahi-daemon
case "$1" in
    start)
	$DAEMON -c || $DAEMON -D
	;;
    stop)
	$DAEMON -c && $DAEMON -k
	;;
    reload)
	$DAEMON -c && $DAEMON -r
	;;
    *)
	echo "Usage: S50avahi-daemon {start|stop|reload}" >&2
	exit 1
	;;
esac
