name: Build atom-skygaze
on:
  push:
    branches: 
      - main
      - build
  pull_request:
    branches: main
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create build directory
        run: mkdir -p build
      
      - name: Download Buildroot and toolchains
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd build
          curl -o - https://buildroot.org/downloads/buildroot-2024.02.tar.gz | tar zxvf -
          git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/Dafang-Hacks/mips-gcc472-glibc216-64bit

      - name: Setup Buildroot
        run: |
          cd build/buildroot-2024.02
          make defconfig BR2_DEFCONFIG=$GITHUB_WORKSPACE/configs/atomskygaze_workflow_defconfig
          # Add some configuration for custom packages.
          echo 'BR2_PACKAGE_BUSYBOX_INIT=y' >> .config
          echo 'BR2_PACKAGE_BUSYBOX_INIT_CONFIG="../../configs/busybox-init.config"' >> .config
          cp -r $GITHUB_WORKSPACE/custompackages/package/* package/

      - name: Setup rust
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
          rustup toolchain install nightly
          source $HOME/.cargo/env
      
      - name: Patch minimp4.rs
        run: |
          cd $GITHUB_WORKSPACE/submodules/minimp4.rs
          patch -p1 < $GITHUB_WORKSPACE/patches/minimp4.patch
      
      - name: Build initramfs
        run: |
          cd build/buildroot-2024.02
          $GITHUB_WORKSPACE/buildscripts/make_initramfs.sh .
      

