name: Build atom-skygaze
on:
  push:
    branches: 
      - main
      - build
  pull_request:
    branches: main
    
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create build directory
        run: mkdir -p build
      
      - name: Download Buildroot and toolchains
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd build
          curl -o - https://buildroot.org/downloads/buildroot-2024.02.tar.gz | tar zxvf -
          git clone https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/Dafang-Hacks/mips-gcc472-glibc216-64bit

      - name: Setup Buildroot
        run: |
          cd build/buildroot-2024.02
          make defconfig BR2_DEFCONFIG=$GITHUB_WORKSPACE/configs/atomskygaze_defconfig

      - name: Build
        run: |
          cd build/buildroot-2024.02
          $GITHUB_WORKSPACE/buildscripts/make_initramfs.sh .  

